"""Store the abstract generated by IARAG's abstraction service."""

from fastapi import APIRouter, HTTPException

from app.shared import events, neo4j
from app.shared.documents import require_document
from app.shared.models import DocRef

router = APIRouter()


class AbstractIn(DocRef):
    abstract: str


@router.post("/documents/abstract")
def save_abstract(body: AbstractIn):
    if not body.abstract.strip():
        raise HTTPException(422, "empty abstract")
    require_document(body.collection, body.id)
    neo4j.write("MATCH (d:Document {uid: $uid}) SET d.abstract = $abstract, d.abstract_at = timestamp()",
                uid=neo4j.uid(body.collection, body.id), abstract=body.abstract.strip())
    events.stage(body.collection, body.id, "l1_extraction")
    return {"collection": body.collection, "id": body.id}
